include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'cabildo-tf/vente/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-custom-image.yml'

stages:
  - test
  - pre-package
  - package
  - post-package
  - deploy

variables:
  PROJECT_PARENT_NAME: monitoring

check-rules:
  stage: test
  image: ${DOCKER_IMAGE}
  variables:
    DOCKER_IMAGE: docker:stable
    DIND_IMAGE: docker:dind
  services:
    - ${DIND_IMAGE}
  script:
    - ./check-rules.sh

.deploy:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
    SERVICES_TO_CHECK: ${PROJECT_PARENT_NAME}_${CI_PROJECT_NAME}
  environment:
    url: http://${PUBLIC_HOSTNAME}/${CI_PROJECT_NAME}
