groups:
- name: arcgis_enterprise
  rules:
  - alert: arcgis_enterprise_component_is_down
    expr: windows_service_state{name=~".*arcgis.*",state="running"} == 0
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: "Service '{{ $labels.name }}' is down"
      description: "Service '{{ $labels.name }}' on instance '{{ $labels.job }}' has been down for more than 3 minutes."

  - alert: arcgis_enterprise_component_web_adaptor_is_down
    expr: windows_service_state{name="w3svc",state="running"} == 0
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: "Service 'Web Adaptor' is down"
      description: "Service 'Web Adaptor' on instance '{{ $labels.job }}' has been down for more than 3 minutes."

  - alert: arcgis_license_expiration
    expr: count(argis_expiration_license_seconds{can_expire="True"} - time() <  51840000) > 0
    for: 30m
    labels:
      severity: warning
    annotations:
      summary: "ArcGIS License expiration in next days"
      description: "{{ $value }} ArcGIS licenses will expiration in next days"

  - alert: incremental_backup_arcgis_enterprise_not_created
    expr: time() - arcgis_backup_created_date_seconds{type="incremental"} > 691200
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Incremental backup for 'ArcGIS Enterprise' delayed"
      description: Incremental backup for 'ArcGIS Enterprise' delayed for {{humanizeDuration $value}}

  - alert: full_backup_arcgis_enterprise_not_created
    expr: time() - arcgis_backup_created_date_seconds{type="full"} > 2678400
    for: 15m
    labels:
      severity: warning
    annotations:
      description: Full backup for 'ArcGIS Enterprise' database delayed for {{humanizeDuration $value}}

  - alert: reconcile_arcgis_db_not_executed
    expr: time() - arcgis_reconcile_db_executed_date_seconds > 90000
    for: 15m
    labels:
      severity: warning
    annotations:
      description: Reconcile arcgis script execution delayed for {{humanizeDuration $value}}

- name: arcgis_rest_services
  rules:
  - alert: arcgis_rest_service_is_down
    expr: arcgis_service_state{configured_state="started",state="stopped"} == 1
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: "Service '{{ $labels.service_name }}' in folder '{{ $labels.folder }}' is down"
      description: "Service '{{ $labels.service_name }}' in folder '{{ $labels.folder }}' has been down for more than 3 minutes."
