groups:
- name: ArcGIS Enterprise
  rules:
  - alert: ArcGIS Enterprise component DOWN
    expr: wmi_service_state{name=~".*arcgis.*",state="running"} == 0
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: "Service {{ $labels.name }} is down"
      description: "Service {{ $labels.name }} on instance {{ $labels.job }} has been down for more than 3 minutes."
