groups:
- name: Windows Server
  rules:
	- alert: CpuUsage
	  expr: 100 - (avg by (job) (irate(wmi_cpu_time_total{mode="idle"}[2m])) * 100) > 80
	  for: 5m
	  labels:
	    severity: warning
	  annotations:
	    summary: CPU alert for instance '{{$labels.job}}'
	    description: Server {{$labels.job}} CPU usage is at {{$value | printf "%.1f"}}%
      